from typing import Optional
from owui_client.client_base import ResourceBase
from owui_client.models.analytics import (
    ModelAnalyticsResponse,
    UserAnalyticsResponse,
    SummaryResponse,
    DailyStatsResponse,
    TokenUsageResponse,
    ModelChatsResponse,
    ModelOverviewResponse,
)
from owui_client.models.chat_messages import ChatMessageModel


class AnalyticsClient(ResourceBase):
    """
    Client for the Analytics endpoints.

    Provides admin-only access to usage statistics, message analytics,
    token consumption data, and model performance metrics.
    """

    async def get_model_analytics(
        self,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        group_id: Optional[str] = None,
    ) -> ModelAnalyticsResponse:
        """Get message counts per model.

        Returns the number of messages generated by each model, optionally
        filtered by date range and user group.

        Args:
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            group_id: Filter by user group ID.

        Returns:
            `ModelAnalyticsResponse`: Message counts per model, sorted by count descending.
        """
        params = {}
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if group_id is not None:
            params["group_id"] = group_id

        return await self._request(
            "GET",
            "/v1/analytics/models",
            model=ModelAnalyticsResponse,
            params=params,
        )

    async def get_user_analytics(
        self,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        group_id: Optional[str] = None,
        limit: int = 50,
    ) -> UserAnalyticsResponse:
        """Get message counts and token usage per user.

        Returns analytics for each user including message count and token
        consumption, optionally filtered by date range and user group.

        Args:
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            group_id: Filter by user group ID.
            limit: Maximum number of users to return (default 50).

        Returns:
            `UserAnalyticsResponse`: User analytics entries, sorted by message count descending.
        """
        params = {}
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if group_id is not None:
            params["group_id"] = group_id
        if limit != 50:
            params["limit"] = limit

        return await self._request(
            "GET",
            "/v1/analytics/users",
            model=UserAnalyticsResponse,
            params=params,
        )

    async def get_messages(
        self,
        model_id: Optional[str] = None,
        user_id: Optional[str] = None,
        chat_id: Optional[str] = None,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> list[ChatMessageModel]:
        """Query messages with filters.

        Retrieves chat messages filtered by model, user, or chat ID.
        If no filter is specified, returns an empty list.

        Args:
            model_id: Filter by model ID.
            user_id: Filter by user ID.
            chat_id: Filter by chat ID (takes precedence over other filters).
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            skip: Number of messages to skip for pagination.
            limit: Maximum number of messages to return (default 50, max 100).

        Returns:
            List of `ChatMessageModel` matching the filters.
        """
        params = {}
        if model_id is not None:
            params["model_id"] = model_id
        if user_id is not None:
            params["user_id"] = user_id
        if chat_id is not None:
            params["chat_id"] = chat_id
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if skip != 0:
            params["skip"] = skip
        if limit != 50:
            params["limit"] = limit

        return await self._request(
            "GET",
            "/v1/analytics/messages",
            model=list[ChatMessageModel],
            params=params,
        )

    async def get_summary(
        self,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        group_id: Optional[str] = None,
    ) -> SummaryResponse:
        """Get summary statistics for the dashboard.

        Returns aggregated counts of messages, chats, models, and users
        within the optional date and group filters.

        Args:
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            group_id: Filter by user group ID.

        Returns:
            `SummaryResponse`: Aggregated summary statistics.
        """
        params = {}
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if group_id is not None:
            params["group_id"] = group_id

        return await self._request(
            "GET",
            "/v1/analytics/summary",
            model=SummaryResponse,
            params=params,
        )

    async def get_daily_stats(
        self,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        group_id: Optional[str] = None,
        granularity: str = "daily",
    ) -> DailyStatsResponse:
        """Get message counts grouped by model for time-series chart.

        Returns daily or hourly message counts per model, suitable for
        rendering time-series charts.

        Args:
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            group_id: Filter by user group ID.
            granularity: Time grouping, either 'daily' or 'hourly' (default 'daily').

        Returns:
            `DailyStatsResponse`: Time-series data sorted chronologically.
        """
        params = {}
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if group_id is not None:
            params["group_id"] = group_id
        if granularity != "daily":
            params["granularity"] = granularity

        return await self._request(
            "GET",
            "/v1/analytics/daily",
            model=DailyStatsResponse,
            params=params,
        )

    async def get_token_usage(
        self,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        group_id: Optional[str] = None,
    ) -> TokenUsageResponse:
        """Get token usage aggregated by model.

        Returns token consumption statistics broken down by model,
        including input, output, and total tokens.

        Args:
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            group_id: Filter by user group ID.

        Returns:
            `TokenUsageResponse`: token usage per model with aggregated totals.
        """
        params = {}
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if group_id is not None:
            params["group_id"] = group_id

        return await self._request(
            "GET",
            "/v1/analytics/tokens",
            model=TokenUsageResponse,
            params=params,
        )

    async def get_model_chats(
        self,
        model_id: str,
        start_date: Optional[int] = None,
        end_date: Optional[int] = None,
        skip: int = 0,
        limit: int = 50,
    ) -> ModelChatsResponse:
        """Get chats that used a specific model.

        Returns chat summaries including the first message preview and
        user information for chats that used the given model.

        Args:
            model_id: The model ID to filter by. Supports path-style IDs.
            start_date: Start timestamp (Unix epoch) for filtering.
            end_date: End timestamp (Unix epoch) for filtering.
            skip: Number of chats to skip for pagination.
            limit: Maximum number of chats to return (default 50, max 100).

        Returns:
            `ModelChatsResponse`: Chat summaries and total count.
        """
        params = {}
        if start_date is not None:
            params["start_date"] = start_date
        if end_date is not None:
            params["end_date"] = end_date
        if skip != 0:
            params["skip"] = skip
        if limit != 50:
            params["limit"] = limit

        return await self._request(
            "GET",
            f"/v1/analytics/models/{model_id}/chats",
            model=ModelChatsResponse,
            params=params,
        )

    async def get_model_overview(
        self,
        model_id: str,
        days: int = 30,
    ) -> ModelOverviewResponse:
        """Get model overview with feedback history and chat tags.

        Returns daily feedback ratings (won/lost) and the top 10 most
        used tags across chats for the specified model.

        Args:
            model_id: The model ID to get the overview for. Supports path-style IDs.
            days: Number of days of history to include (0 for all time, default 30).

        Returns:
            `ModelOverviewResponse`: Feedback history and tag statistics.
        """
        params = {}
        if days != 30:
            params["days"] = days

        return await self._request(
            "GET",
            f"/v1/analytics/models/{model_id}/overview",
            model=ModelOverviewResponse,
            params=params,
        )
