from typing import Optional
from pydantic import BaseModel


class ModelAnalyticsEntry(BaseModel):
    """
    Analytics entry for a single model, showing message count.
    """

    model_id: str
    """ID of the model."""

    count: int
    """Number of messages generated by this model."""


class ModelAnalyticsResponse(BaseModel):
    """
    Response containing message counts per model.
    """

    models: list[ModelAnalyticsEntry]
    """List of model analytics entries, sorted by count descending."""


class UserAnalyticsEntry(BaseModel):
    """
    Analytics entry for a single user, showing message count and token usage.
    """

    user_id: str
    """ID of the user."""

    name: Optional[str] = None
    """Display name of the user."""

    email: Optional[str] = None
    """Email address of the user."""

    count: int
    """Number of messages sent by this user."""

    input_tokens: int = 0
    """Total input tokens consumed by this user."""

    output_tokens: int = 0
    """Total output tokens generated for this user."""

    total_tokens: int = 0
    """Total token count (input + output) for this user."""


class UserAnalyticsResponse(BaseModel):
    """
    Response containing message counts and token usage per user.
    """

    users: list[UserAnalyticsEntry]
    """List of user analytics entries, sorted by message count descending."""


class SummaryResponse(BaseModel):
    """
    Summary statistics for the analytics dashboard.
    """

    total_messages: int
    """Total number of messages across all models."""

    total_chats: int
    """Total number of unique chats."""

    total_models: int
    """Total number of unique models used."""

    total_users: int
    """Total number of unique users."""


class DailyStatsEntry(BaseModel):
    """
    Message counts grouped by model for a single date.
    """

    date: str
    """Date string in ISO format (YYYY-MM-DD) or hourly format (YYYY-MM-DD HH:00)."""

    models: dict[str, int]
    """Mapping of model ID to message count for this date.

    Dict Fields:
        - `<model_id>` (int, required): Message count for the specific model
    """


class DailyStatsResponse(BaseModel):
    """
    Response containing daily message counts grouped by model.
    """

    data: list[DailyStatsEntry]
    """List of daily stats entries, sorted chronologically."""


class TokenUsageEntry(BaseModel):
    """
    Usage statistics for tokens consumed by a single model.
    """

    model_id: str
    """ID of the model."""

    input_tokens: int
    """Total input tokens consumed."""

    output_tokens: int
    """Total output tokens generated."""

    total_tokens: int
    """Total token count (input + output)."""

    message_count: int
    """Number of messages using this model."""


class TokenUsageResponse(BaseModel):
    """
    Response containing token usage aggregated by model.
    """

    models: list[TokenUsageEntry]
    """List of token usage entries per model, sorted by total_tokens descending."""

    total_input_tokens: int
    """Sum of input tokens across all models."""

    total_output_tokens: int
    """Sum of output tokens across all models."""

    total_tokens: int
    """Sum of total tokens across all models."""


class ModelChatEntry(BaseModel):
    """
    Summary of a chat that used a specific model.
    """

    chat_id: str
    """ID of the chat."""

    user_id: Optional[str] = None
    """ID of the user who started the chat."""

    user_name: Optional[str] = None
    """Name of the user who started the chat."""

    first_message: Optional[str] = None
    """Preview of the first user message (truncated to 200 characters)."""

    updated_at: int
    """Timestamp of the most recent message in the chat (Unix epoch)."""


class ModelChatsResponse(BaseModel):
    """
    Response containing chats that used a specific model.
    """

    chats: list[ModelChatEntry]
    """List of chat summaries."""

    total: int
    """Total number of chats in the response."""


class HistoryEntry(BaseModel):
    """
    Daily feedback history entry for a model.
    """

    date: str
    """Date string in ISO format (YYYY-MM-DD)."""

    won: int = 0
    """Number of positive ratings (+1) on this date."""

    lost: int = 0
    """Number of negative ratings (-1) on this date."""


class TagEntry(BaseModel):
    """
    Tag usage entry for a model.
    """

    tag: str
    """Tag name."""

    count: int
    """Number of chats with this tag."""


class ModelOverviewResponse(BaseModel):
    """
    Response containing model overview with feedback history and chat tags.
    """

    history: list[HistoryEntry]
    """Daily feedback history, one entry per day in the range."""

    tags: list[TagEntry]
    """Top 10 most used tags across chats for this model, sorted by count descending."""
